# Site settings
title: Jonathan DeLaigle
email: delaigle.jonathan@gmail.com
description: ""
baseurl: ""
highlighter: pygments
url: "http://www.grndlvl.com"
exclude:
  - atom.xml
  - feed.xml

# Build settings
markdown: kramdown
permalink: pretty
