# Site settings
title: Jonathan DeLaigle
email: delaigle.jonathan@gmail.com
description: ""
baseurl: ""
highlighter: pygments
url: "http://grndlvl.com"

# Build settings
markdown: kramdown
permalink: pretty
